### ISSUE TITLE
Undo/Redo Crash

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/flexlay#71]
1) Open a level, 2) Create an object, 3) Move the object. These last two changes are added to the undo stack.
Click Undo. The movement is undone.
Click Undo. The object is deleted. (using remove() method of a list)
Click Redo. The object is then created (append() to that list)
Click Redo. Here, something goes wrong. Somewhere in the past 2 steps, the reference to the object in the move command has been affected, and now, although the object is added, it no longer works properly: 

```
QPainter::begin: Painter already active
Traceback (most recent call last):
  File "/home/stekar/git/supertux/flexlay/flexlay/gui/editor_map_widget.py", line 111, in paintEvent
    self.workspace.draw(self.gc)
  File "/home/stekar/git/supertux/flexlay/flexlay/workspace.py", line 32, in draw
    self.editor_map.draw(gc)
  File "/home/stekar/git/supertux/flexlay/flexlay/editor_map.py", line 104, in draw
    layer.draw(gc)
  File "/home/stekar/git/supertux/flexlay/flexlay/object_layer.py", line 32, in draw
    if obj.to_draw and gc.get_clip_rect().is_overlapped(obj.get_bound_rect()):
  File "/home/stekar/git/supertux/flexlay/flexlay/objmap_sprite_object.py", line 55, in get_bound_rect
    return Rectf(self.pos - origin - align,
TypeError: unsupported operand type(s) for -: 'NoneType' and 'Point'
```

**Comment by tobbi** [comment]
Any of self.pos or origin or align is None, for some reason. Does this work if you revert 217640f88139294eac872a2e715b43cf5517fc59 ?

**Comment by Karkus476** [comment]
@tobbi No. It looks a little different (some things still get painted), but the traceback is still spammed.

**Comment by Karkus476** [comment]
It is clear that when removed from the list the actual object is cleaned up from memory (although it shouldn't be, as there is still a reference) therefore a fix might be to copy the object?
